# Generated by Django 5.2.7 on 2026-02-01 18:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'langue',
                'verbose_name_plural': 'langues',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20, verbose_name='rôle')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('type', models.CharField(choices=[('homework', 'Devoir'), ('exam', 'Examen'), ('project', 'Projet')], max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('closed', 'Terminé')], default='draft', max_length=20, verbose_name='statut')),
                ('due_date', models.DateTimeField(verbose_name="date d'échéance")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.language', verbose_name='langue')),
            ],
            options={
                'verbose_name': 'devoir',
                'verbose_name_plural': 'devoirs',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('session_reminder', 'Rappel de séance'), ('payment_due', 'Paiement dû'), ('certificate_ready', 'Certificat disponible'), ('evaluation_ready', 'Évaluation disponible'), ('system', 'Système')], max_length=20, verbose_name='type de notification')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='photo de profil')),
                ('city', models.CharField(max_length=50, verbose_name='ville')),
                ('country', models.CharField(max_length=50, verbose_name='pays')),
                ('number', models.CharField(max_length=20, verbose_name='numéro de téléphone')),
                ('address', models.CharField(max_length=100, verbose_name='adresse')),
                ('about', models.TextField(default=' ', max_length=1000, verbose_name='à propos')),
                ('theme_preference', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10, verbose_name='préférence de thème')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profils',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(editable=False, max_length=20, unique=True, verbose_name='matricule')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name="date d'inscription")),
                ('total_hours_purchased', models.IntegerField(default=0, verbose_name='heures totales achetées')),
                ('total_hours_used', models.IntegerField(default=0, verbose_name='heures totales utilisées')),
                ('languages', models.ManyToManyField(related_name='students', to='dashboard.language', verbose_name='langues')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'étudiant',
                'verbose_name_plural': 'étudiants',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/%Y/%m/%d/', verbose_name='fichier')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('resource_type', models.CharField(choices=[('document', 'Document'), ('link', 'Lien'), ('video', 'Vidéo'), ('other', 'Autre')], max_length=20, verbose_name='type de ressource')),
                ('access_type', models.CharField(choices=[('all_students', 'Tous les étudiants'), ('specific_students', 'Étudiants spécifiques'), ('course_students', "Étudiants d'un cours spécifique")], default='all_students', max_length=20, verbose_name="type d'accès")),
                ('is_visible', models.BooleanField(default=True, verbose_name='visible')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name="disponible jusqu'au")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('languages', models.ManyToManyField(blank=True, related_name='resources', to='dashboard.language', verbose_name='langues concernées')),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL, verbose_name='téléchargé par')),
                ('students', models.ManyToManyField(blank=True, related_name='resources', to='dashboard.student', verbose_name='étudiants ciblés')),
            ],
            options={
                'verbose_name': 'ressource pédagogique',
                'verbose_name_plural': 'ressources pédagogiques',
                'ordering': ['-created_at'],
                'permissions': [('assign_resource', 'Peut assigner des ressources aux étudiants'), ('manage_resource', 'Peut gérer toutes les ressources')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(auto_created=True, blank=True, max_length=50, unique=True, verbose_name='numéro de facture')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('hours_purchased', models.IntegerField(verbose_name='heures achetées')),
                ('hours_remaining', models.IntegerField(verbose_name='heures restantes')),
                ('payment_type', models.CharField(choices=[('hourly', "À l'heure"), ('package', "Pack d'heures"), ('subscription', 'Abonnement')], max_length=20, verbose_name='type de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='statut')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='date de paiement')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="date d'expiration")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dashboard.student', verbose_name='étudiant')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50, verbose_name='niveau')),
                ('issued_date', models.DateField(auto_now_add=True, verbose_name="date d'émission")),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='fichier du certificat')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.language', verbose_name='langue')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='dashboard.student', verbose_name='étudiant')),
            ],
            options={
                'verbose_name': 'certificat',
                'verbose_name_plural': 'certificats',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=100, verbose_name='spécialité')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name="date d'inscription")),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='taux horaire')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('languages', models.ManyToManyField(related_name='teachers', to='dashboard.language', verbose_name='langues')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'enseignant',
                'verbose_name_plural': 'enseignants',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='current_teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='current_students', to='dashboard.teacher', verbose_name='enseignants actuels'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='heure de début')),
                ('end_time', models.TimeField(verbose_name='heure de fin')),
                ('status', models.CharField(choices=[('scheduled', 'Prévue'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('rescheduled', 'Reportée'), ('absent', 'Absence')], default='scheduled', max_length=20, verbose_name='statut')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('meeting_link', models.URLField(verbose_name='lien de réunion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.language', verbose_name='langue')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dashboard.student', verbose_name='étudiant')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dashboard.teacher', verbose_name='enseignant')),
            ],
            options={
                'verbose_name': 'séance',
                'verbose_name_plural': 'séances',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('absence', "Justification d'absence"), ('document', 'Demande de document'), ('meeting', 'Demande de rendez-vous'), ('other', 'Autre')], max_length=20, verbose_name='type de demande')),
                ('subject', models.CharField(max_length=200, verbose_name='sujet')),
                ('description', models.TextField(verbose_name='description')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='request_attachments/', verbose_name='pièce jointe')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='statut')),
                ('response', models.TextField(blank=True, null=True, verbose_name='réponse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='dashboard.student', verbose_name='étudiant')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='dashboard.teacher', verbose_name='enseignant')),
            ],
            options={
                'verbose_name': 'demande',
                'verbose_name_plural': 'demandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('pronunciation', 'Prononciation'), ('grammar', 'Grammaire'), ('vocabulary', 'Vocabulaire'), ('fluency', 'Fluidité'), ('comprehension', 'Compréhension')], max_length=20, verbose_name="type d'évaluation")),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='score')),
                ('comments', models.TextField(blank=True, verbose_name='commentaires')),
                ('evaluation_date', models.DateField(auto_now_add=True, verbose_name="date d'évaluation")),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.language', verbose_name='langue')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='dashboard.student', verbose_name='étudiant')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='dashboard.teacher', verbose_name='enseignant')),
            ],
            options={
                'verbose_name': 'évaluation',
                'verbose_name_plural': 'évaluations',
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/', verbose_name='fichier')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='date de soumission')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='feedback')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='dashboard.assignment', verbose_name='devoir')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student', verbose_name='étudiant')),
            ],
            options={
                'verbose_name': 'soumission',
                'verbose_name_plural': 'soumissions',
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=10, verbose_name='jour')),
                ('classroom', models.CharField(blank=True, max_length=30, null=True, verbose_name='salle de cours')),
                ('start_time', models.TimeField(verbose_name='heure de début')),
                ('end_time', models.TimeField(verbose_name='heure de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.language', verbose_name='languages')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.student', verbose_name='étudiant')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.teacher', verbose_name='enseignant')),
            ],
            options={
                'verbose_name': 'emploi du temps',
                'verbose_name_plural': 'emplois du temps',
                'ordering': ['day', 'start_time'],
                'unique_together': {('day', 'language', 'teacher', 'student', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='commentaire')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Note de 1 (mauvais) à 5 (excellent)', verbose_name='note')),
                ('comment_at', models.DateTimeField(auto_now_add=True, verbose_name='date du commentaire')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='étudiant')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboard.language', verbose_name='langue')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboard.teacher', verbose_name='enseignant')),
            ],
            options={
                'verbose_name': 'commentaire',
                'verbose_name_plural': 'commentaires',
                'ordering': ['-comment_at'],
                'unique_together': {('student', 'teacher', 'language')},
            },
        ),
    ]
