# Generated by Django 5.2.7 on 2026-02-01 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='resource',
            name='teachers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teachers_resources', to='dashboard.teacher', verbose_name='enseignant responsable'),
            preserve_default=False,
        ),
    ]
