# Generated by Django 5.2.7 on 2025-11-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
