# Generated by Django 5.2.7 on 2026-01-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
    ]
