# Generated by Django 5.2.7 on 2026-05-15 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='appreciation_pedagogique',
            field=models.TextField(blank=True, verbose_name='appréciation pédagogique'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='ID du certificat'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='competences_validees',
            field=models.TextField(blank=True, verbose_name='compétences validées'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='duree_formation',
            field=models.CharField(blank=True, max_length=100, verbose_name='durée de formation'),
        ),
        migrations.AddField(
            model_name='session',
            name='comp_comprehension',
            field=models.BooleanField(default=False, verbose_name='Compréhension'),
        ),
        migrations.AddField(
            model_name='session',
            name='comp_ecrit',
            field=models.BooleanField(default=False, verbose_name='Écrit'),
        ),
        migrations.AddField(
            model_name='session',
            name='comp_grammaire',
            field=models.BooleanField(default=False, verbose_name='Grammaire'),
        ),
        migrations.AddField(
            model_name='session',
            name='comp_oral',
            field=models.BooleanField(default=False, verbose_name='Oral'),
        ),
        migrations.AddField(
            model_name='session',
            name='comp_vocabulaire',
            field=models.BooleanField(default=False, verbose_name='Vocabulaire'),
        ),
        migrations.AddField(
            model_name='session',
            name='comprehension_score',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Faible'), (2, '2 - Passable'), (3, '3 - Bien'), (4, '4 - Excellent')], null=True, verbose_name='compréhension (1-4)'),
        ),
        migrations.AddField(
            model_name='session',
            name='description_devoir',
            field=models.TextField(blank=True, verbose_name='description du devoir'),
        ),
        migrations.AddField(
            model_name='session',
            name='devoir_donne',
            field=models.BooleanField(default=False, verbose_name='devoir donné'),
        ),
        migrations.AddField(
            model_name='session',
            name='difficultes',
            field=models.TextField(blank=True, verbose_name='difficultés rencontrées'),
        ),
        migrations.AddField(
            model_name='session',
            name='duree_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='durée (minutes)'),
        ),
        migrations.AddField(
            model_name='session',
            name='engagement',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Faible'), (2, '2 - Passable'), (3, '3 - Bien'), (4, '4 - Excellent')], null=True, verbose_name='engagement (1-4)'),
        ),
        migrations.AddField(
            model_name='session',
            name='fiche_completee',
            field=models.BooleanField(default=False, verbose_name='fiche complétée'),
        ),
        migrations.AddField(
            model_name='session',
            name='observations_formateur',
            field=models.TextField(blank=True, verbose_name='observations du formateur'),
        ),
        migrations.AddField(
            model_name='session',
            name='participation',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Faible'), (2, '2 - Passable'), (3, '3 - Bien'), (4, '4 - Excellent')], null=True, verbose_name='participation (1-4)'),
        ),
        migrations.AddField(
            model_name='session',
            name='prochaine_etape',
            field=models.TextField(blank=True, verbose_name='prochaine étape pédagogique'),
        ),
        migrations.AddField(
            model_name='session',
            name='seance_realisee',
            field=models.BooleanField(default=False, verbose_name='séance réalisée'),
        ),
        migrations.AddField(
            model_name='session',
            name='statut_validation',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=20, verbose_name='statut de validation'),
        ),
        migrations.AddField(
            model_name='session',
            name='theme_cours',
            field=models.CharField(blank=True, max_length=200, verbose_name='thème du cours'),
        ),
        migrations.AddField(
            model_name='session',
            name='type_seance',
            field=models.CharField(choices=[('individuelle', 'Individuelle'), ('groupe', 'Groupe')], default='individuelle', max_length=20, verbose_name='type de séance'),
        ),
        migrations.AddField(
            model_name='student',
            name='objectif_formation',
            field=models.TextField(blank=True, verbose_name='objectif de formation'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='taux_remuneration',
            field=models.DecimalField(decimal_places=2, default=55.0, max_digits=5, verbose_name='taux de rémunération (%)'),
        ),
        migrations.AlterField(
            model_name='session',
            name='meeting_link',
            field=models.URLField(blank=True, null=True, verbose_name='lien de réunion'),
        ),
        migrations.AlterField(
            model_name='student',
            name='statuts',
            field=models.CharField(choices=[('actif', 'Actif'), ('pause', 'Pause'), ('terminé', 'Terminé'), ('abandon', 'Abandon'), ('attente', 'En attente')], max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('disponible', 'Disponible'), ('conge', 'En congé'), ('plein', 'Plein'), ('inactif', 'Inactif')], default='disponible', max_length=20, verbose_name='statut'),
        ),
        migrations.CreateModel(
            name='PaiementFormateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant (€)')),
                ('montant_calcule', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='montant calculé (55% CA)')),
                ('periode_debut', models.DateField(verbose_name='début de période')),
                ('periode_fin', models.DateField(verbose_name='fin de période')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('partiel', 'Partiel')], default='en_attente', max_length=20, verbose_name='statut')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='date de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_formateur', to='dashboard.teacher', verbose_name='formateur')),
            ],
            options={
                'verbose_name': 'paiement formateur',
                'verbose_name_plural': 'paiements formateurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
