# Generated by Django 5.2.7 on 2026-05-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_certificate_appreciation_pedagogique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="sessions_m2m",
                to="dashboard.student",
                verbose_name="étudiants",
            ),
        ),
        migrations.AlterField(
            model_name="paiementformateur",
            name="montant",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="montant (MAD)"
            ),
        ),
    ]
