# Generated by Django 5.2.7 on 2026-01-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_teacher_to_request'),
    ]

    operations = [
    ]
