# Generated by Django 5.2.7 on 2026-02-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_resource_uploaded_by_resource_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='statuts',
            field=models.CharField(choices=[('actif', 'Actif'), ('abandon', 'Abandon'), ('terminé', 'Terminé'), ('attente', 'En attente')], default=1, max_length=20, verbose_name='statut'),
            preserve_default=False,
        ),
    ]
