# Generated by Django 5.2.7 on 2026-01-28 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_add_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'devoir', 'verbose_name_plural': 'devoirs'},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'student__user__first_name'], 'verbose_name': 'présence', 'verbose_name_plural': 'présences'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issued_date'], 'verbose_name': 'certificat', 'verbose_name_plural': 'certificats'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_at'], 'verbose_name': 'commentaire', 'verbose_name_plural': 'commentaires'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'ordering': ['-evaluation_date'], 'verbose_name': 'évaluation', 'verbose_name_plural': 'évaluations'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'langue', 'verbose_name_plural': 'langues'},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name': 'note', 'verbose_name_plural': 'notes'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'paiement', 'verbose_name_plural': 'paiements'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profil', 'verbose_name_plural': 'profils'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'verbose_name': 'demande', 'verbose_name_plural': 'demandes'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-created_at'], 'verbose_name': 'ressource pédagogique', 'verbose_name_plural': 'ressources pédagogiques'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day', 'start_time'], 'verbose_name': 'emploi du temps', 'verbose_name_plural': 'emplois du temps'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date', '-start_time'], 'verbose_name': 'séance', 'verbose_name_plural': 'séances'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'compétence', 'verbose_name_plural': 'compétences'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'étudiant', 'verbose_name_plural': 'étudiants'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'soumission', 'verbose_name_plural': 'soumissions'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'enseignant', 'verbose_name_plural': 'enseignants'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='current_teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='current_students', to='dashboard.teacher', verbose_name='enseignants actuels'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(verbose_name="date d'échéance"),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.skill', verbose_name='compétence'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('closed', 'Terminé')], default='draft', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=200, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('homework', 'Devoir'), ('exam', 'Examen'), ('project', 'Projet')], max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name="heure d'arrivée"),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='dashboard.session', verbose_name='séance'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.skill', verbose_name='compétence'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('late', 'En retard'), ('excused', 'Justifié')], max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student', verbose_name='étudiant'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.teacher', verbose_name='enseignant'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='fichier du certificat'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_date',
            field=models.DateField(auto_now_add=True, verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.language', verbose_name='langue'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='level',
            field=models.CharField(max_length=50, verbose_name='niveau'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='dashboard.student', verbose_name='étudiant'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='commentaire'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date du commentaire'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboard.language', verbose_name='langue'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Note de 1 (mauvais) à 5 (excellent)', verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='étudiant'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboard.teacher', verbose_name='enseignant'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20, verbose_name='rôle'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='comments',
            field=models.TextField(blank=True, verbose_name='commentaires'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_date',
            field=models.DateField(auto_now_add=True, verbose_name="date d'évaluation"),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_type',
            field=models.CharField(choices=[('pronunciation', 'Prononciation'), ('grammar', 'Grammaire'), ('vocabulary', 'Vocabulaire'), ('fluency', 'Fluidité'), ('comprehension', 'Compréhension')], max_length=20, verbose_name="type d'évaluation"),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.language', verbose_name='langue'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='dashboard.student', verbose_name='étudiant'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='dashboard.teacher', verbose_name='enseignant'),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='language',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='comment',
            field=models.TextField(blank=True, verbose_name='commentaire'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.skill', verbose_name='compétence'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student', verbose_name='étudiant'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='lu'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('session_reminder', 'Rappel de séance'), ('payment_due', 'Paiement dû'), ('certificate_ready', 'Certificat disponible'), ('evaluation_ready', 'Évaluation disponible'), ('system', 'Système')], max_length=20, verbose_name='type de notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name="date d'expiration"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='hours_purchased',
            field=models.IntegerField(verbose_name='heures achetées'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='hours_remaining',
            field=models.IntegerField(verbose_name='heures restantes'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(auto_created=True, blank=True, max_length=50, unique=True, verbose_name='numéro de facture'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('hourly', "À l'heure"), ('package', "Pack d'heures"), ('subscription', 'Abonnement')], max_length=20, verbose_name='type de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dashboard.student', verbose_name='étudiant'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default=' ', max_length=1000, verbose_name='à propos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=100, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=50, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=50, verbose_name='pays'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(max_length=20, verbose_name='numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='photo de profil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10, verbose_name='préférence de thème'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='request',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='request_attachments/', verbose_name='pièce jointe'),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('absence', "Justification d'absence"), ('document', 'Demande de document'), ('meeting', 'Demande de rendez-vous'), ('other', 'Autre')], max_length=20, verbose_name='type de demande'),
        ),
        migrations.AlterField(
            model_name='request',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='réponse'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='request',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='dashboard.student', verbose_name='étudiant'),
        ),
        migrations.AlterField(
            model_name='request',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='sujet'),
        ),
        migrations.AlterField(
            model_name='request',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='dashboard.teacher', verbose_name='enseignant'),
        ),
        migrations.AlterField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/', verbose_name='fichier'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='languages',
            field=models.ManyToManyField(related_name='resources', to='dashboard.language', verbose_name='langues'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('document', 'Document'), ('link', 'Lien'), ('video', 'Vidéo'), ('other', 'Autre')], max_length=20, verbose_name='type de ressource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='skills',
            field=models.ManyToManyField(blank=True, to='dashboard.skill', verbose_name='compétences'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=200, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='téléchargé par'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='salle de classe'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=10, verbose_name='jour'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(verbose_name='heure de fin'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.language', verbose_name='langue'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.skill', verbose_name='compétence'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(verbose_name='heure de début'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.student', verbose_name='étudiant'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.teacher', verbose_name='enseignant'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(verbose_name='heure de fin'),
        ),
        migrations.AlterField(
            model_name='session',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='feedback'),
        ),
        migrations.AlterField(
            model_name='session',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.language', verbose_name='langue'),
        ),
        migrations.AlterField(
            model_name='session',
            name='meeting_link',
            field=models.URLField(verbose_name='lien de réunion'),
        ),
        migrations.AlterField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(verbose_name='heure de début'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Prévue'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('rescheduled', 'Reportée'), ('absent', 'Absence')], default='scheduled', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dashboard.student', verbose_name='étudiant'),
        ),
        migrations.AlterField(
            model_name='session',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dashboard.teacher', verbose_name='enseignant'),
        ),
        migrations.AlterField(
            model_name='session',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='students',
            field=models.ManyToManyField(to='dashboard.student', verbose_name='étudiants'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='teachers',
            field=models.ManyToManyField(to='dashboard.teacher', verbose_name='enseignants'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="date d'inscription"),
        ),
        migrations.AlterField(
            model_name='student',
            name='languages',
            field=models.ManyToManyField(related_name='students', to='dashboard.language', verbose_name='langues'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='matricule'),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_hours_purchased',
            field=models.IntegerField(default=0, verbose_name='heures totales achetées'),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_hours_used',
            field=models.IntegerField(default=0, verbose_name='heures totales utilisées'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='dashboard.assignment', verbose_name='devoir'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='feedback'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to='submissions/', verbose_name='fichier'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.mark', verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student', verbose_name='étudiant'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de soumission'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="date d'inscription"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='taux horaire'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='disponible'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='languages',
            field=models.ManyToManyField(related_name='teachers', to='dashboard.language', verbose_name='langues'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='speciality',
            field=models.CharField(max_length=100, verbose_name='spécialité'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
    ]
