# Generated by Django 5.2.7 on 2026-02-11 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_student_statuts'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='languages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments_language', to='dashboard.language'),
            preserve_default=False,
        ),
    ]
