# Generated by Django 5.2.7 on 2026-05-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_session_migrate_student_to_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="student",
        ),
        migrations.AlterField(
            model_name="session",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="sessions",
                to="dashboard.student",
                verbose_name="étudiants",
            ),
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
