# Generated by Django 5.2.7 on 2026-01-30 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_assignment_options_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('day', 'language', 'teacher', 'student', 'start_time')},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='salle de cours'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.language', verbose_name='languages'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='skill',
        ),
    ]
