# Generated by Django 5.2.7 on 2026-02-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_payment_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('conge', 'En congé'), ('plein', 'Plein'), ('inactif', 'Inactif')], default=1, max_length=20, verbose_name='statut'),
            preserve_default=False,
        ),
    ]
