# Generated by Django 5.2.7 on 2026-01-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='meeting_link',
            field=models.URLField(),
        ),
    ]
