# Generated by Django 5.2.7 on 2026-02-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_teacher_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_available',
        ),
    ]
