# Generated by Django 5.2.7 on 2026-01-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_session_meeting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/assets/img/profile.png', null=True, upload_to='profile_pics/'),
        ),
    ]
