# Generated by Django 5.2.7 on 2026-02-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_teacher_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-created_at'], 'verbose_name': 'ressource pédagogique', 'verbose_name_plural': 'ressources pédagogiques'},
        ),
    ]
