# Generated by Django 5.2.7 on 2026-05-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_notification_add_evaluation_request_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="theme_preference",
        ),
    ]
