# Generated by Django 5.2.7 on 2026-01-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(auto_created=True, blank=True, max_length=50, unique=True),
        ),
    ]
