# Generated by Django 5.2.7 on 2026-05-22 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_remove_theme_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="series_index",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="index dans la série"
            ),
        ),
        migrations.CreateModel(
            name="SessionSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ],
                        verbose_name="jour de la semaine",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="heure de début")),
                ("end_time", models.TimeField(verbose_name="heure de fin")),
                (
                    "recurrence_start",
                    models.DateField(verbose_name="début de la série"),
                ),
                (
                    "recurrence_end",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="fin de la série (vide = 12 mois)",
                    ),
                ),
                (
                    "type_seance",
                    models.CharField(
                        choices=[
                            ("individuelle", "Individuelle"),
                            ("groupe", "Groupe"),
                        ],
                        default="individuelle",
                        max_length=20,
                        verbose_name="type de séance",
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="lien de réunion"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.language",
                        verbose_name="langue",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="session_series",
                        to="dashboard.student",
                        verbose_name="étudiants",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_series",
                        to="dashboard.teacher",
                        verbose_name="formateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "série de séances",
                "verbose_name_plural": "séries de séances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="session",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrences",
                to="dashboard.sessionseries",
                verbose_name="série récurrente",
            ),
        ),
    ]
