# Generated by Django 5.2.7 on 2026-02-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_resource_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='access_type',
        ),
    ]
