# Generated by Django 5.2.7 on 2026-01-26 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_payment_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='dashboard.teacher'),
        ),
    ]
