# Generated by Django 5.2.7 on 2026-05-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_sessionseries_and_session_series_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='event_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='couleur de la séance'),
        ),
    ]
