# Generated by Django 5.2.7 on 2026-01-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_request_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='current_teachers',
            field=models.ManyToManyField(blank=True, related_name='students', to='dashboard.teacher'),
        ),
    ]
