# Generated by Django 5.1.6 on 2025-08-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/profile.png', null=True, upload_to='profile_pics/'),
        ),
    ]
