# Generated by Django 5.1.6 on 2025-08-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='skills',
            field=models.ManyToManyField(blank=True, to='dashboard.skill'),
        ),
    ]
