# Generated by Django 5.1.6 on 2025-08-10 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_resource_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.student'),
        ),
    ]
