# Generated by Django 5.1.6 on 2025-08-02 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_student_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='branch',
            name='type_formation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='skills',
        ),
        migrations.AddField(
            model_name='student',
            name='current_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='dashboard.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_hours_purchased',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='total_hours_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('pronunciation', 'Prononciation'), ('grammar', 'Grammaire'), ('vocabulary', 'Vocabulaire'), ('fluency', 'Fluidité'), ('comprehension', 'Compréhension')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comments', models.TextField(blank=True)),
                ('evaluation_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='dashboard.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='dashboard.teacher')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.language')),
            ],
            options={
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='dashboard.student')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.language')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='languages',
            field=models.ManyToManyField(related_name='resources', to='dashboard.language'),
        ),
        migrations.AddField(
            model_name='student',
            name='languages',
            field=models.ManyToManyField(related_name='students', to='dashboard.language'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='languages',
            field=models.ManyToManyField(related_name='teachers', to='dashboard.language'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('session_reminder', 'Rappel de séance'), ('payment_due', 'Paiement dû'), ('certificate_ready', 'Certificat disponible'), ('evaluation_ready', 'Évaluation disponible'), ('system', 'Système')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hours_purchased', models.IntegerField()),
                ('hours_remaining', models.IntegerField()),
                ('payment_type', models.CharField(choices=[('hourly', "À l'heure"), ('package', "Pack d'heures"), ('subscription', 'Abonnement')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dashboard.student')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Prévue'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('rescheduled', 'Reportée'), ('absent', 'Absence')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.language')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dashboard.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dashboard.teacher')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.DeleteModel(
            name='TrainingType',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
