# Generated by Django 5.1.6 on 2025-08-11 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_schedule_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_object_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_object_type',
        ),
    ]
