# Generated by Django 5.1.6 on 2025-08-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='comment_at',
        ),
    ]
